#! /bin/sh

sxhkd &

# pkill compton; compton --config ~/.configcompton.conf & 


#Mouse Focus
bspc config focus_follows_pointer false
bspc config click_to_focus true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          12
bspc config border_width         3

# was 0.52
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity     first_child

# Hopefully switch node direction

######### STARTUPS #########
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# emacs startups floating for some reason..must be caps for some reason too
bspc rule -a Emacs state=tiled 

## Auto Starts ##

# Wallpaper
nitrogen --restore &

# No mouse when not needed
unclutter &

# Network manager
nm-applet & 

# Polybar
#$HOME/.config/polybar/launch.sh
polybar example &

# Music
mpd &

# Stay on
caffeine &

#
#X stuff
#
# No beeps plz
xset b off &
# Reload cursor theme
#xsetroot -cursor_name left_ptr

#bspc wm --adopt-orphans


## For emacs 
setxkbmap -option ctrl:swapcaps &     # Swap Left Control and Caps Lock
#setxkbmap -option ctrl:nocaps  &     # Make Caps Lock a Control key
